server:
  port: 8888
spring:
  application:
    name: server-java
  cloud:
    nacos:
      username: nacos
      password: nacos
      discovery:
        server-addr: localhost:8848
        namespace: xxx
